### PR TITLE
Enable peerDependency of jsdom@^12.0.0

### PR DESCRIPTION
**Pull request by petersendidit**
This enables the use of jsdom 12 and future versions without having to update the `peerDependencies`. I also keeps backward compatibility with the example that has been in the readme to change the `userAgent`.

### CODE REVIEW

**Comment by petersendidit** [comment]
Got the tests to pass by adding some backwards compatibility code to handle the userAgent. Figured because there was a test for it and it was documented in the readme it was an important feature. This doesn't prevent the use of the ResourceLoader from directly being passed in as an option, just keeps the existing configurations that just pass in the userAgent from failing.

**Comment by petersendidit** [comment]
@badeball Anything else needed on this to get this merged and released?

**Comment by badeball** [comment]
Hi, @petersendidit 

I'm sorry for the late reply. I don't get to take as much time for this as I want to.

I haven't ignored the pull request though, but experimented a little bit myself. You see, I stumbled across  some issues with updating myself, which I've outlined in https://github.com/badeball/karma-jsdom-launcher/issues/24.

> And I'm holding of on updating until the underlying issue has been identified and determined to not be an issue for the launcher itself. Any help is obviously very welcomed here.

**Comment by badeball** [comment]
> Got the tests to pass by adding some backwards compatibility code to handle the userAgent. Figured because there was a test for it and it was documented in the readme it was an important feature.

This isn't entirely what I'm looking for in the launcher. The idea is to give control to the user and enable them to control the details - not specifically let them change user agent. The change in how user agent is now configured is what lead me to attempt to run Karma programmatically and where I discovered the problem outlined in the above-mentioned issue.

**Comment by badeball** [comment]
Fixed with release of v6.1.5.

**Pull request closed without merging**
